# Generated by Django 2.2.5 on 2020-02-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200114_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guests',
            field=models.IntegerField(help_text='How many people wiil be staying?'),
        ),
    ]
