# Generated by Django 2.2.5 on 2020-04-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20200411_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
